name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libpcap-dev \
          libjson-c-dev \
          pkg-config \
          libgtest-dev

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install \
          cmake \
          libpcap \
          json-c \
          pkg-config \
          googletest

    - name: Build
      run: |
        make clean
        make BUILD_TYPE=${{matrix.build_type}}

    - name: Verify executable
      run: |
        ls -la bin/
        ./bin/http-sniffer --help

    - name: Run unit tests
      run: |
        make test